#!/bin/bash

NAME="plates"
DJANGODIR=/plates/plates-project
USER=root
NUM_WORKERS=5
DJANGO_SETTINGS_MODULE=plates.settings
DJANGO_WSGI_MODULE=plates.wsgi

cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER \
  --bind=0.0.0.0:8000 \
  --log-level=debug \
  --log-file=-
