# Generated by Django 2.2 on 2019-09-11 07:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plates_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Format does not comply. ex. а888тт88rus ', regex='^\\w{1}\\d{3}\\w{2}\\d{2,3}rus')])),
                ('car_model', models.CharField(max_length=250)),
                ('model_image', models.ImageField(blank=True, upload_to='model_images', verbose_name='Car model image')),
            ],
        ),
        migrations.CreateModel(
            name='PersonId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('PT', 'PASSPORT'), ('DL', 'DRIVER_LISENCE'), ('DEL', 'DELETED')], max_length=100)),
                ('value', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='plates_app.PersonId')),
                ('plates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='plates_app.NumberPlate')),
            ],
        ),
    ]
